-- Do not edit directly: autogenerated sql
DROP TABLE IF EXISTS mimiciv_local.tokenevents;
CREATE TABLE mimiciv_local.tokenevents AS (
    WITH meds AS (
        SELECT mimiciv_icu.inputevents.stay_id AS stay_id,
            generate_series(
                mimiciv_icu.inputevents.starttime,
                mimiciv_icu.inputevents.endtime,
                '1 hour'
            ) AS charttime,
            mimiciv_icu.d_items.label AS token_label,
            mimiciv_icu.inputevents.amountuom AS uom_label,
            CASE
                WHEN (
                    mimiciv_icu.inputevents.endtime - mimiciv_icu.inputevents.starttime > make_interval(secs => 3600.0)
                ) THEN mimiciv_icu.inputevents.amount / CAST(
                    (
                        EXTRACT(
                            epoch
                            FROM mimiciv_icu.inputevents.endtime - mimiciv_icu.inputevents.starttime
                        ) / CAST(3600 AS NUMERIC)
                    ) AS NUMERIC
                )
                ELSE mimiciv_icu.inputevents.amount
            END AS dose
        FROM mimiciv_icu.inputevents
            JOIN mimiciv_icu.d_items ON mimiciv_icu.d_items.itemid = mimiciv_icu.inputevents.itemid
    ),
    med_values AS (
        SELECT meds.stay_id AS stay_id,
            meds.charttime AS charttime,
            meds.token_label AS token_label,
            meds.uom_label AS uom_label,
            meds.dose AS dose,
            CAST(
                floor(
                    percent_rank() OVER (
                        PARTITION BY meds.token_label,
                        meds.uom_label
                        ORDER BY meds.dose
                    ) * 10
                ) AS INTEGER
            ) AS token_value_disc
        FROM meds
    ),
    vitalsign_tokenized AS (
        SELECT mimiciv_derived.vitalsign.stay_id AS stay_id,
            mimiciv_derived.vitalsign.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM mimiciv_derived.vitalsign
            JOIN LATERAL (
                VALUES (
                        'vitalsign.heart_rate',
                        mimiciv_derived.vitalsign.heart_rate,
                        mimiciv_derived.vitalsign.heart_rate IS NULL
                    ),
                    (
                        'vitalsign.sbp',
                        mimiciv_derived.vitalsign.sbp,
                        mimiciv_derived.vitalsign.sbp IS NULL
                    ),
                    (
                        'vitalsign.dbp',
                        mimiciv_derived.vitalsign.dbp,
                        mimiciv_derived.vitalsign.dbp IS NULL
                    ),
                    (
                        'vitalsign.resp_rate',
                        mimiciv_derived.vitalsign.resp_rate,
                        mimiciv_derived.vitalsign.resp_rate IS NULL
                    ),
                    (
                        'vitalsign.spo2',
                        mimiciv_derived.vitalsign.spo2,
                        mimiciv_derived.vitalsign.spo2 IS NULL
                    ),
                    (
                        'vitalsign.glucose',
                        mimiciv_derived.vitalsign.glucose,
                        mimiciv_derived.vitalsign.glucose IS NULL
                    ),
                    (
                        concat(
                            'vitalsign.temperature.',
                            CAST(
                                mimiciv_derived.vitalsign.temperature_site AS VARCHAR
                            )
                        ),
                        mimiciv_derived.vitalsign.temperature,
                        mimiciv_derived.vitalsign.temperature IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    crrt_tokenized AS (
        SELECT mimiciv_derived.crrt.stay_id AS stay_id,
            mimiciv_derived.crrt.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM mimiciv_derived.crrt
            JOIN LATERAL (
                VALUES (
                        'crrt.access_pressure',
                        mimiciv_derived.crrt.access_pressure,
                        mimiciv_derived.crrt.access_pressure IS NULL
                    ),
                    (
                        'crrt.blood_flow',
                        mimiciv_derived.crrt.blood_flow,
                        mimiciv_derived.crrt.blood_flow IS NULL
                    ),
                    (
                        'crrt.citrate',
                        mimiciv_derived.crrt.citrate,
                        mimiciv_derived.crrt.citrate IS NULL
                    ),
                    (
                        'crrt.current_goal',
                        mimiciv_derived.crrt.current_goal,
                        mimiciv_derived.crrt.current_goal IS NULL
                    ),
                    (
                        'crrt.dialysate_rate',
                        mimiciv_derived.crrt.dialysate_rate,
                        mimiciv_derived.crrt.dialysate_rate IS NULL
                    ),
                    (
                        'crrt.effluent_pressure',
                        mimiciv_derived.crrt.effluent_pressure,
                        mimiciv_derived.crrt.effluent_pressure IS NULL
                    ),
                    (
                        'crrt.filter_pressure',
                        mimiciv_derived.crrt.filter_pressure,
                        mimiciv_derived.crrt.filter_pressure IS NULL
                    ),
                    (
                        'crrt.heparin_dose',
                        mimiciv_derived.crrt.heparin_dose,
                        mimiciv_derived.crrt.heparin_dose IS NULL
                    ),
                    (
                        'crrt.hourly_patient_fluid_removal',
                        mimiciv_derived.crrt.hourly_patient_fluid_removal,
                        mimiciv_derived.crrt.hourly_patient_fluid_removal IS NULL
                    ),
                    (
                        'crrt.prefilter_replacement_rate',
                        mimiciv_derived.crrt.prefilter_replacement_rate,
                        mimiciv_derived.crrt.prefilter_replacement_rate IS NULL
                    ),
                    (
                        'crrt.postfilter_replacement_rate',
                        mimiciv_derived.crrt.postfilter_replacement_rate,
                        mimiciv_derived.crrt.postfilter_replacement_rate IS NULL
                    ),
                    (
                        'crrt.replacement_rate',
                        mimiciv_derived.crrt.replacement_rate,
                        mimiciv_derived.crrt.replacement_rate IS NULL
                    ),
                    (
                        'crrt.return_pressure',
                        mimiciv_derived.crrt.return_pressure,
                        mimiciv_derived.crrt.return_pressure IS NULL
                    ),
                    (
                        'crrt.ultrafiltrate_output',
                        mimiciv_derived.crrt.ultrafiltrate_output,
                        mimiciv_derived.crrt.ultrafiltrate_output IS NULL
                    ),
                    (
                        concat(
                            'crrt.crrt_mode.',
                            CAST(mimiciv_derived.crrt.crrt_mode AS TEXT)
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.crrt.crrt_mode IS NULL
                    ),
                    (
                        concat(
                            'crrt.dialysate_fluid.',
                            CAST(mimiciv_derived.crrt.dialysate_fluid AS TEXT)
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.crrt.dialysate_fluid IS NULL
                    ),
                    (
                        concat(
                            'crrt.heparin_concentration.',
                            CAST(
                                mimiciv_derived.crrt.heparin_concentration AS TEXT
                            )
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.crrt.heparin_concentration IS NULL
                    ),
                    (
                        concat(
                            'crrt.replacement_fluid.',
                            CAST(mimiciv_derived.crrt.replacement_fluid AS TEXT)
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.crrt.replacement_fluid IS NULL
                    ),
                    (
                        concat(
                            'crrt.system_active.',
                            CAST(mimiciv_derived.crrt.system_active AS TEXT)
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.crrt.system_active IS NULL
                    ),
                    (
                        concat(
                            'crrt.clots.',
                            CAST(mimiciv_derived.crrt.clots AS TEXT)
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.crrt.clots IS NULL
                    ),
                    (
                        concat(
                            'crrt.clots_increasing.',
                            CAST(mimiciv_derived.crrt.clots_increasing AS TEXT)
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.crrt.clots_increasing IS NULL
                    ),
                    (
                        concat(
                            'crrt.clotted.',
                            CAST(mimiciv_derived.crrt.clotted AS TEXT)
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.crrt.clotted IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    chemistry_aligned AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.chemistry.subject_id AS subject_id,
            mimiciv_derived.chemistry.hadm_id AS hadm_id,
            mimiciv_derived.chemistry.charttime AS charttime,
            mimiciv_derived.chemistry.specimen_id AS specimen_id,
            mimiciv_derived.chemistry.albumin AS albumin,
            mimiciv_derived.chemistry.globulin AS globulin,
            mimiciv_derived.chemistry.total_protein AS total_protein,
            mimiciv_derived.chemistry.aniongap AS aniongap,
            mimiciv_derived.chemistry.bicarbonate AS bicarbonate,
            mimiciv_derived.chemistry.bun AS bun,
            mimiciv_derived.chemistry.calcium AS calcium,
            mimiciv_derived.chemistry.chloride AS chloride,
            mimiciv_derived.chemistry.creatinine AS creatinine,
            mimiciv_derived.chemistry.glucose AS glucose,
            mimiciv_derived.chemistry.sodium AS sodium,
            mimiciv_derived.chemistry.potassium AS potassium
        FROM mimiciv_derived.chemistry
            JOIN mimiciv_derived.icustay_detail ON mimiciv_derived.chemistry.subject_id = mimiciv_derived.icustay_detail.subject_id
            AND mimiciv_derived.chemistry.charttime >= mimiciv_derived.icustay_detail.icu_intime
            AND mimiciv_derived.chemistry.charttime <= mimiciv_derived.icustay_detail.icu_outtime
        WHERE mimiciv_derived.icustay_detail.stay_id IS NOT NULL
    ),
    chemistry_tokenized AS (
        SELECT chemistry_aligned.stay_id AS stay_id,
            chemistry_aligned.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM chemistry_aligned
            JOIN LATERAL (
                VALUES (
                        'chemistry.albumin',
                        chemistry_aligned.albumin,
                        chemistry_aligned.albumin IS NULL
                    ),
                    (
                        'chemistry.globulin',
                        chemistry_aligned.globulin,
                        chemistry_aligned.globulin IS NULL
                    ),
                    (
                        'chemistry.total_protein',
                        chemistry_aligned.total_protein,
                        chemistry_aligned.total_protein IS NULL
                    ),
                    (
                        'chemistry.bicarbonate',
                        chemistry_aligned.bicarbonate,
                        chemistry_aligned.bicarbonate IS NULL
                    ),
                    (
                        'chemistry.bun',
                        chemistry_aligned.bun,
                        chemistry_aligned.bun IS NULL
                    ),
                    (
                        'chemistry.calcium',
                        chemistry_aligned.calcium,
                        chemistry_aligned.calcium IS NULL
                    ),
                    (
                        'chemistry.chloride',
                        chemistry_aligned.chloride,
                        chemistry_aligned.chloride IS NULL
                    ),
                    (
                        'chemistry.creatinine',
                        chemistry_aligned.creatinine,
                        chemistry_aligned.creatinine IS NULL
                    ),
                    (
                        'chemistry.glucose',
                        chemistry_aligned.glucose,
                        chemistry_aligned.glucose IS NULL
                    ),
                    (
                        'chemistry.sodium',
                        chemistry_aligned.sodium,
                        chemistry_aligned.sodium IS NULL
                    ),
                    (
                        'chemistry.potassium',
                        chemistry_aligned.potassium,
                        chemistry_aligned.potassium IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    complete_blood_count_aligned AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.complete_blood_count.subject_id AS subject_id,
            mimiciv_derived.complete_blood_count.hadm_id AS hadm_id,
            mimiciv_derived.complete_blood_count.charttime AS charttime,
            mimiciv_derived.complete_blood_count.specimen_id AS specimen_id,
            mimiciv_derived.complete_blood_count.hematocrit AS hematocrit,
            mimiciv_derived.complete_blood_count.hemoglobin AS hemoglobin,
            mimiciv_derived.complete_blood_count.mch AS mch,
            mimiciv_derived.complete_blood_count.mchc AS mchc,
            mimiciv_derived.complete_blood_count.mcv AS mcv,
            mimiciv_derived.complete_blood_count.platelet AS platelet,
            mimiciv_derived.complete_blood_count.rbc AS rbc,
            mimiciv_derived.complete_blood_count.rdw AS rdw,
            mimiciv_derived.complete_blood_count.rdwsd AS rdwsd,
            mimiciv_derived.complete_blood_count.wbc AS wbc
        FROM mimiciv_derived.complete_blood_count
            JOIN mimiciv_derived.icustay_detail ON mimiciv_derived.complete_blood_count.subject_id = mimiciv_derived.icustay_detail.subject_id
            AND mimiciv_derived.complete_blood_count.charttime >= mimiciv_derived.icustay_detail.icu_intime
            AND mimiciv_derived.complete_blood_count.charttime <= mimiciv_derived.icustay_detail.icu_outtime
        WHERE mimiciv_derived.icustay_detail.stay_id IS NOT NULL
    ),
    complete_blood_count_tokenized AS (
        SELECT complete_blood_count_aligned.stay_id AS stay_id,
            complete_blood_count_aligned.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM complete_blood_count_aligned
            JOIN LATERAL (
                VALUES (
                        'complete_blood_count.hematocrit',
                        complete_blood_count_aligned.hematocrit,
                        complete_blood_count_aligned.hematocrit IS NULL
                    ),
                    (
                        'complete_blood_count.hemoglobin',
                        complete_blood_count_aligned.hemoglobin,
                        complete_blood_count_aligned.hemoglobin IS NULL
                    ),
                    (
                        'complete_blood_count.mch',
                        complete_blood_count_aligned.mch,
                        complete_blood_count_aligned.mch IS NULL
                    ),
                    (
                        'complete_blood_count.mchc',
                        complete_blood_count_aligned.mchc,
                        complete_blood_count_aligned.mchc IS NULL
                    ),
                    (
                        'complete_blood_count.mcv',
                        complete_blood_count_aligned.mcv,
                        complete_blood_count_aligned.mcv IS NULL
                    ),
                    (
                        'complete_blood_count.platelet',
                        complete_blood_count_aligned.platelet,
                        complete_blood_count_aligned.platelet IS NULL
                    ),
                    (
                        'complete_blood_count.rbc',
                        complete_blood_count_aligned.rbc,
                        complete_blood_count_aligned.rbc IS NULL
                    ),
                    (
                        'complete_blood_count.rdw',
                        complete_blood_count_aligned.rdw,
                        complete_blood_count_aligned.rdw IS NULL
                    ),
                    (
                        'complete_blood_count.rdwsd',
                        complete_blood_count_aligned.rdwsd,
                        complete_blood_count_aligned.rdwsd IS NULL
                    ),
                    (
                        'complete_blood_count.wbc',
                        complete_blood_count_aligned.wbc,
                        complete_blood_count_aligned.wbc IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    blood_differential_aligned AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.blood_differential.subject_id AS subject_id,
            mimiciv_derived.blood_differential.hadm_id AS hadm_id,
            mimiciv_derived.blood_differential.charttime AS charttime,
            mimiciv_derived.blood_differential.specimen_id AS specimen_id,
            mimiciv_derived.blood_differential.wbc AS wbc,
            mimiciv_derived.blood_differential.basophils_abs AS basophils_abs,
            mimiciv_derived.blood_differential.eosinophils_abs AS eosinophils_abs,
            mimiciv_derived.blood_differential.lymphocytes_abs AS lymphocytes_abs,
            mimiciv_derived.blood_differential.monocytes_abs AS monocytes_abs,
            mimiciv_derived.blood_differential.neutrophils_abs AS neutrophils_abs,
            mimiciv_derived.blood_differential.basophils AS basophils,
            mimiciv_derived.blood_differential.eosinophils AS eosinophils,
            mimiciv_derived.blood_differential.lymphocytes AS lymphocytes,
            mimiciv_derived.blood_differential.monocytes AS monocytes,
            mimiciv_derived.blood_differential.neutrophils AS neutrophils,
            mimiciv_derived.blood_differential.atypical_lymphocytes AS atypical_lymphocytes,
            mimiciv_derived.blood_differential.bands AS bands,
            mimiciv_derived.blood_differential.immature_granulocytes AS immature_granulocytes,
            mimiciv_derived.blood_differential.metamyelocytes AS metamyelocytes,
            mimiciv_derived.blood_differential.nrbc AS nrbc
        FROM mimiciv_derived.blood_differential
            JOIN mimiciv_derived.icustay_detail ON mimiciv_derived.blood_differential.subject_id = mimiciv_derived.icustay_detail.subject_id
            AND mimiciv_derived.blood_differential.charttime >= mimiciv_derived.icustay_detail.icu_intime
            AND mimiciv_derived.blood_differential.charttime <= mimiciv_derived.icustay_detail.icu_outtime
        WHERE mimiciv_derived.icustay_detail.stay_id IS NOT NULL
    ),
    blood_differential_tokenized AS (
        SELECT blood_differential_aligned.stay_id AS stay_id,
            blood_differential_aligned.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM blood_differential_aligned
            JOIN LATERAL (
                VALUES (
                        'blood_differential.wbc',
                        blood_differential_aligned.wbc,
                        blood_differential_aligned.wbc IS NULL
                    ),
                    (
                        'blood_differential.basophils_abs',
                        blood_differential_aligned.basophils_abs,
                        blood_differential_aligned.basophils_abs IS NULL
                    ),
                    (
                        'blood_differential.eosinophils_abs',
                        blood_differential_aligned.eosinophils_abs,
                        blood_differential_aligned.eosinophils_abs IS NULL
                    ),
                    (
                        'blood_differential.lymphocytes_abs',
                        blood_differential_aligned.lymphocytes_abs,
                        blood_differential_aligned.lymphocytes_abs IS NULL
                    ),
                    (
                        'blood_differential.monocytes_abs',
                        blood_differential_aligned.monocytes_abs,
                        blood_differential_aligned.monocytes_abs IS NULL
                    ),
                    (
                        'blood_differential.neutrophils_abs',
                        blood_differential_aligned.neutrophils_abs,
                        blood_differential_aligned.neutrophils_abs IS NULL
                    ),
                    (
                        'blood_differential.basophils',
                        blood_differential_aligned.basophils,
                        blood_differential_aligned.basophils IS NULL
                    ),
                    (
                        'blood_differential.eosinophils',
                        blood_differential_aligned.eosinophils,
                        blood_differential_aligned.eosinophils IS NULL
                    ),
                    (
                        'blood_differential.lymphocytes',
                        blood_differential_aligned.lymphocytes,
                        blood_differential_aligned.lymphocytes IS NULL
                    ),
                    (
                        'blood_differential.monocytes',
                        blood_differential_aligned.monocytes,
                        blood_differential_aligned.monocytes IS NULL
                    ),
                    (
                        'blood_differential.neutrophils',
                        blood_differential_aligned.neutrophils,
                        blood_differential_aligned.neutrophils IS NULL
                    ),
                    (
                        'blood_differential.atypical_lymphocytes',
                        blood_differential_aligned.atypical_lymphocytes,
                        blood_differential_aligned.atypical_lymphocytes IS NULL
                    ),
                    (
                        'blood_differential.bands',
                        blood_differential_aligned.bands,
                        blood_differential_aligned.bands IS NULL
                    ),
                    (
                        'blood_differential.immature_granulocytes',
                        blood_differential_aligned.immature_granulocytes,
                        blood_differential_aligned.immature_granulocytes IS NULL
                    ),
                    (
                        'blood_differential.metamyelocytes',
                        blood_differential_aligned.metamyelocytes,
                        blood_differential_aligned.metamyelocytes IS NULL
                    ),
                    (
                        'blood_differential.nrbc',
                        blood_differential_aligned.nrbc,
                        blood_differential_aligned.nrbc IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    bg_aligned AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.bg.subject_id AS subject_id,
            mimiciv_derived.bg.hadm_id AS hadm_id,
            mimiciv_derived.bg.charttime AS charttime,
            mimiciv_derived.bg.specimen AS specimen,
            mimiciv_derived.bg.so2 AS so2,
            mimiciv_derived.bg.po2 AS po2,
            mimiciv_derived.bg.pco2 AS pco2,
            mimiciv_derived.bg.fio2_chartevents AS fio2_chartevents,
            mimiciv_derived.bg.fio2 AS fio2,
            mimiciv_derived.bg.aado2 AS aado2,
            mimiciv_derived.bg.aado2_calc AS aado2_calc,
            mimiciv_derived.bg.pao2fio2ratio AS pao2fio2ratio,
            mimiciv_derived.bg.ph AS ph,
            mimiciv_derived.bg.baseexcess AS baseexcess,
            mimiciv_derived.bg.bicarbonate AS bicarbonate,
            mimiciv_derived.bg.totalco2 AS totalco2,
            mimiciv_derived.bg.hematocrit AS hematocrit,
            mimiciv_derived.bg.hemoglobin AS hemoglobin,
            mimiciv_derived.bg.carboxyhemoglobin AS carboxyhemoglobin,
            mimiciv_derived.bg.methemoglobin AS methemoglobin,
            mimiciv_derived.bg.chloride AS chloride,
            mimiciv_derived.bg.calcium AS calcium,
            mimiciv_derived.bg.temperature AS temperature,
            mimiciv_derived.bg.potassium AS potassium,
            mimiciv_derived.bg.sodium AS sodium,
            mimiciv_derived.bg.lactate AS lactate,
            mimiciv_derived.bg.glucose AS glucose
        FROM mimiciv_derived.bg
            JOIN mimiciv_derived.icustay_detail ON mimiciv_derived.bg.subject_id = mimiciv_derived.icustay_detail.subject_id
            AND mimiciv_derived.bg.charttime >= mimiciv_derived.icustay_detail.icu_intime
            AND mimiciv_derived.bg.charttime <= mimiciv_derived.icustay_detail.icu_outtime
        WHERE mimiciv_derived.icustay_detail.stay_id IS NOT NULL
    ),
    bg_tokenized AS (
        SELECT bg_aligned.stay_id AS stay_id,
            bg_aligned.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM bg_aligned
            JOIN LATERAL (
                VALUES ('bg.so2', bg_aligned.so2, bg_aligned.so2 IS NULL),
                    ('bg.po2', bg_aligned.po2, bg_aligned.po2 IS NULL),
                    (
                        'bg.pco2',
                        bg_aligned.pco2,
                        bg_aligned.pco2 IS NULL
                    ),
                    (
                        'bg.fio2_chartevents',
                        bg_aligned.fio2_chartevents,
                        bg_aligned.fio2_chartevents IS NULL
                    ),
                    (
                        'bg.fio2',
                        bg_aligned.fio2,
                        bg_aligned.fio2 IS NULL
                    ),
                    (
                        'bg.aado2',
                        bg_aligned.aado2,
                        bg_aligned.aado2 IS NULL
                    ),
                    (
                        'bg.aado2_calc',
                        bg_aligned.aado2_calc,
                        bg_aligned.aado2_calc IS NULL
                    ),
                    (
                        'bg.pao2fio2ratio',
                        bg_aligned.pao2fio2ratio,
                        bg_aligned.pao2fio2ratio IS NULL
                    ),
                    ('bg.ph', bg_aligned.ph, bg_aligned.ph IS NULL),
                    (
                        'bg.baseexcess',
                        bg_aligned.baseexcess,
                        bg_aligned.baseexcess IS NULL
                    ),
                    (
                        'bg.bicarbonate',
                        bg_aligned.bicarbonate,
                        bg_aligned.bicarbonate IS NULL
                    ),
                    (
                        'bg.totalco2',
                        bg_aligned.totalco2,
                        bg_aligned.totalco2 IS NULL
                    ),
                    (
                        'bg.hematocrit',
                        bg_aligned.hematocrit,
                        bg_aligned.hematocrit IS NULL
                    ),
                    (
                        'bg.hemoglobin',
                        bg_aligned.hemoglobin,
                        bg_aligned.hemoglobin IS NULL
                    ),
                    (
                        'bg.carboxyhemoglobin',
                        bg_aligned.carboxyhemoglobin,
                        bg_aligned.carboxyhemoglobin IS NULL
                    ),
                    (
                        'bg.methemoglobin',
                        bg_aligned.methemoglobin,
                        bg_aligned.methemoglobin IS NULL
                    ),
                    (
                        'bg.chloride',
                        bg_aligned.chloride,
                        bg_aligned.chloride IS NULL
                    ),
                    (
                        'bg.calcium',
                        bg_aligned.calcium,
                        bg_aligned.calcium IS NULL
                    ),
                    (
                        'bg.temperature',
                        bg_aligned.temperature,
                        bg_aligned.temperature IS NULL
                    ),
                    (
                        'bg.potassium',
                        bg_aligned.potassium,
                        bg_aligned.potassium IS NULL
                    ),
                    (
                        'bg.sodium',
                        bg_aligned.sodium,
                        bg_aligned.sodium IS NULL
                    ),
                    (
                        'bg.lactate',
                        bg_aligned.lactate,
                        bg_aligned.lactate IS NULL
                    ),
                    (
                        'bg.glucose',
                        bg_aligned.glucose,
                        bg_aligned.glucose IS NULL
                    ),
                    (
                        concat(
                            'bg.specimen.',
                            CAST(bg_aligned.specimen AS TEXT)
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        bg_aligned.specimen IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    cardiac_marker_aligned AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.cardiac_marker.subject_id AS subject_id,
            mimiciv_derived.cardiac_marker.hadm_id AS hadm_id,
            mimiciv_derived.cardiac_marker.charttime AS charttime,
            mimiciv_derived.cardiac_marker.specimen_id AS specimen_id,
            mimiciv_derived.cardiac_marker.troponin_t AS troponin_t,
            mimiciv_derived.cardiac_marker.ck_mb AS ck_mb,
            mimiciv_derived.cardiac_marker.ntprobnp AS ntprobnp
        FROM mimiciv_derived.cardiac_marker
            JOIN mimiciv_derived.icustay_detail ON mimiciv_derived.cardiac_marker.subject_id = mimiciv_derived.icustay_detail.subject_id
            AND mimiciv_derived.cardiac_marker.charttime >= mimiciv_derived.icustay_detail.icu_intime
            AND mimiciv_derived.cardiac_marker.charttime <= mimiciv_derived.icustay_detail.icu_outtime
        WHERE mimiciv_derived.icustay_detail.stay_id IS NOT NULL
    ),
    cardiac_marker_tokenized AS (
        SELECT cardiac_marker_aligned.stay_id AS stay_id,
            cardiac_marker_aligned.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM cardiac_marker_aligned
            JOIN LATERAL (
                VALUES (
                        'cardiac_marker.troponin_t',
                        cardiac_marker_aligned.troponin_t,
                        cardiac_marker_aligned.troponin_t IS NULL
                    ),
                    (
                        'cardiac_marker.ck_mb',
                        cardiac_marker_aligned.ck_mb,
                        cardiac_marker_aligned.ck_mb IS NULL
                    ),
                    (
                        'cardiac_marker.ntprobnp',
                        cardiac_marker_aligned.ntprobnp,
                        cardiac_marker_aligned.ntprobnp IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    coagulation_aligned AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.coagulation.subject_id AS subject_id,
            mimiciv_derived.coagulation.hadm_id AS hadm_id,
            mimiciv_derived.coagulation.charttime AS charttime,
            mimiciv_derived.coagulation.specimen_id AS specimen_id,
            mimiciv_derived.coagulation.d_dimer AS d_dimer,
            mimiciv_derived.coagulation.fibrinogen AS fibrinogen,
            mimiciv_derived.coagulation.thrombin AS thrombin,
            mimiciv_derived.coagulation.inr AS inr,
            mimiciv_derived.coagulation.pt AS pt,
            mimiciv_derived.coagulation.ptt AS ptt
        FROM mimiciv_derived.coagulation
            JOIN mimiciv_derived.icustay_detail ON mimiciv_derived.coagulation.subject_id = mimiciv_derived.icustay_detail.subject_id
            AND mimiciv_derived.coagulation.charttime >= mimiciv_derived.icustay_detail.icu_intime
            AND mimiciv_derived.coagulation.charttime <= mimiciv_derived.icustay_detail.icu_outtime
        WHERE mimiciv_derived.icustay_detail.stay_id IS NOT NULL
    ),
    coagulation_tokenized AS (
        SELECT coagulation_aligned.stay_id AS stay_id,
            coagulation_aligned.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM coagulation_aligned
            JOIN LATERAL (
                VALUES (
                        'coagulation.d_dimer',
                        coagulation_aligned.d_dimer,
                        coagulation_aligned.d_dimer IS NULL
                    ),
                    (
                        'coagulation.fibrinogen',
                        coagulation_aligned.fibrinogen,
                        coagulation_aligned.fibrinogen IS NULL
                    ),
                    (
                        'coagulation.thrombin',
                        coagulation_aligned.thrombin,
                        coagulation_aligned.thrombin IS NULL
                    ),
                    (
                        'coagulation.inr',
                        coagulation_aligned.inr,
                        coagulation_aligned.inr IS NULL
                    ),
                    (
                        'coagulation.pt',
                        coagulation_aligned.pt,
                        coagulation_aligned.pt IS NULL
                    ),
                    (
                        'coagulation.ptt',
                        coagulation_aligned.ptt,
                        coagulation_aligned.ptt IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    enzyme_aligned AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.enzyme.subject_id AS subject_id,
            mimiciv_derived.enzyme.hadm_id AS hadm_id,
            mimiciv_derived.enzyme.charttime AS charttime,
            mimiciv_derived.enzyme.specimen_id AS specimen_id,
            mimiciv_derived.enzyme.alt AS alt,
            mimiciv_derived.enzyme.alp AS alp,
            mimiciv_derived.enzyme.ast AS ast,
            mimiciv_derived.enzyme.amylase AS amylase,
            mimiciv_derived.enzyme.bilirubin_total AS bilirubin_total,
            mimiciv_derived.enzyme.bilirubin_direct AS bilirubin_direct,
            mimiciv_derived.enzyme.bilirubin_indirect AS bilirubin_indirect,
            mimiciv_derived.enzyme.ck_cpk AS ck_cpk,
            mimiciv_derived.enzyme.ck_mb AS ck_mb,
            mimiciv_derived.enzyme.ggt AS ggt,
            mimiciv_derived.enzyme.ld_ldh AS ld_ldh
        FROM mimiciv_derived.enzyme
            JOIN mimiciv_derived.icustay_detail ON mimiciv_derived.enzyme.subject_id = mimiciv_derived.icustay_detail.subject_id
            AND mimiciv_derived.enzyme.charttime >= mimiciv_derived.icustay_detail.icu_intime
            AND mimiciv_derived.enzyme.charttime <= mimiciv_derived.icustay_detail.icu_outtime
        WHERE mimiciv_derived.icustay_detail.stay_id IS NOT NULL
    ),
    enzyme_tokenized AS (
        SELECT enzyme_aligned.stay_id AS stay_id,
            enzyme_aligned.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM enzyme_aligned
            JOIN LATERAL (
                VALUES (
                        'enzyme.alt',
                        enzyme_aligned.alt,
                        enzyme_aligned.alt IS NULL
                    ),
                    (
                        'enzyme.alp',
                        enzyme_aligned.alp,
                        enzyme_aligned.alp IS NULL
                    ),
                    (
                        'enzyme.ast',
                        enzyme_aligned.ast,
                        enzyme_aligned.ast IS NULL
                    ),
                    (
                        'enzyme.amylase',
                        enzyme_aligned.amylase,
                        enzyme_aligned.amylase IS NULL
                    ),
                    (
                        'enzyme.bilirubin_total',
                        enzyme_aligned.bilirubin_total,
                        enzyme_aligned.bilirubin_total IS NULL
                    ),
                    (
                        'enzyme.bilirubin_direct',
                        enzyme_aligned.bilirubin_direct,
                        enzyme_aligned.bilirubin_direct IS NULL
                    ),
                    (
                        'enzyme.bilirubin_indirect',
                        enzyme_aligned.bilirubin_indirect,
                        enzyme_aligned.bilirubin_indirect IS NULL
                    ),
                    (
                        'enzyme.ck_cpk',
                        enzyme_aligned.ck_cpk,
                        enzyme_aligned.ck_cpk IS NULL
                    ),
                    (
                        'enzyme.ck_mb',
                        enzyme_aligned.ck_mb,
                        enzyme_aligned.ck_mb IS NULL
                    ),
                    (
                        'enzyme.ggt',
                        enzyme_aligned.ggt,
                        enzyme_aligned.ggt IS NULL
                    ),
                    (
                        'enzyme.ld_ldh',
                        enzyme_aligned.ld_ldh,
                        enzyme_aligned.ld_ldh IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    icp_tokenized AS (
        SELECT mimiciv_derived.icp.stay_id AS stay_id,
            mimiciv_derived.icp.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM mimiciv_derived.icp
            JOIN LATERAL (
                VALUES (
                        'icp.icp',
                        mimiciv_derived.icp.icp,
                        mimiciv_derived.icp.icp IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    urine_output_tokenized AS (
        SELECT mimiciv_derived.urine_output.stay_id AS stay_id,
            mimiciv_derived.urine_output.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM mimiciv_derived.urine_output
            JOIN LATERAL (
                VALUES (
                        'urine_output.urineoutput',
                        mimiciv_derived.urine_output.urineoutput,
                        mimiciv_derived.urine_output.urineoutput IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    ventilator_setting_tokenized AS (
        SELECT mimiciv_derived.ventilator_setting.stay_id AS stay_id,
            mimiciv_derived.ventilator_setting.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM mimiciv_derived.ventilator_setting
            JOIN LATERAL (
                VALUES (
                        'ventilator_setting.respiratory_rate_set',
                        mimiciv_derived.ventilator_setting.respiratory_rate_set,
                        mimiciv_derived.ventilator_setting.respiratory_rate_set IS NULL
                    ),
                    (
                        'ventilator_setting.respiratory_rate_total',
                        mimiciv_derived.ventilator_setting.respiratory_rate_total,
                        mimiciv_derived.ventilator_setting.respiratory_rate_total IS NULL
                    ),
                    (
                        'ventilator_setting.respiratory_rate_spontaneous',
                        mimiciv_derived.ventilator_setting.respiratory_rate_spontaneous,
                        mimiciv_derived.ventilator_setting.respiratory_rate_spontaneous IS NULL
                    ),
                    (
                        'ventilator_setting.minute_volume',
                        mimiciv_derived.ventilator_setting.minute_volume,
                        mimiciv_derived.ventilator_setting.minute_volume IS NULL
                    ),
                    (
                        'ventilator_setting.tidal_volume_set',
                        mimiciv_derived.ventilator_setting.tidal_volume_set,
                        mimiciv_derived.ventilator_setting.tidal_volume_set IS NULL
                    ),
                    (
                        'ventilator_setting.tidal_volume_observed',
                        mimiciv_derived.ventilator_setting.tidal_volume_observed,
                        mimiciv_derived.ventilator_setting.tidal_volume_observed IS NULL
                    ),
                    (
                        'ventilator_setting.tidal_volume_spontaneous',
                        mimiciv_derived.ventilator_setting.tidal_volume_spontaneous,
                        mimiciv_derived.ventilator_setting.tidal_volume_spontaneous IS NULL
                    ),
                    (
                        'ventilator_setting.plateau_pressure',
                        mimiciv_derived.ventilator_setting.plateau_pressure,
                        mimiciv_derived.ventilator_setting.plateau_pressure IS NULL
                    ),
                    (
                        'ventilator_setting.peep',
                        mimiciv_derived.ventilator_setting.peep,
                        mimiciv_derived.ventilator_setting.peep IS NULL
                    ),
                    (
                        'ventilator_setting.fio2',
                        mimiciv_derived.ventilator_setting.fio2,
                        mimiciv_derived.ventilator_setting.fio2 IS NULL
                    ),
                    (
                        'ventilator_setting.flow_rate',
                        mimiciv_derived.ventilator_setting.flow_rate,
                        mimiciv_derived.ventilator_setting.flow_rate IS NULL
                    ),
                    (
                        concat(
                            'ventilator_setting.ventilator_mode.',
                            CAST(
                                mimiciv_derived.ventilator_setting.ventilator_mode AS TEXT
                            )
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.ventilator_setting.ventilator_mode IS NULL
                    ),
                    (
                        concat(
                            'ventilator_setting.ventilator_mode_hamilton.',
                            CAST(
                                mimiciv_derived.ventilator_setting.ventilator_mode_hamilton AS TEXT
                            )
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.ventilator_setting.ventilator_mode_hamilton IS NULL
                    ),
                    (
                        concat(
                            'ventilator_setting.ventilator_type.',
                            CAST(
                                mimiciv_derived.ventilator_setting.ventilator_type AS TEXT
                            )
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        mimiciv_derived.ventilator_setting.ventilator_type IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    inflammation_aligned AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.inflammation.subject_id AS subject_id,
            mimiciv_derived.inflammation.hadm_id AS hadm_id,
            mimiciv_derived.inflammation.charttime AS charttime,
            mimiciv_derived.inflammation.specimen_id AS specimen_id,
            mimiciv_derived.inflammation.crp AS crp
        FROM mimiciv_derived.inflammation
            JOIN mimiciv_derived.icustay_detail ON mimiciv_derived.inflammation.subject_id = mimiciv_derived.icustay_detail.subject_id
            AND mimiciv_derived.inflammation.charttime >= mimiciv_derived.icustay_detail.icu_intime
            AND mimiciv_derived.inflammation.charttime <= mimiciv_derived.icustay_detail.icu_outtime
        WHERE mimiciv_derived.icustay_detail.stay_id IS NOT NULL
    ),
    inflammation_tokenized AS (
        SELECT inflammation_aligned.stay_id AS stay_id,
            inflammation_aligned.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM inflammation_aligned
            JOIN LATERAL (
                VALUES (
                        'inflammation.crp',
                        inflammation_aligned.crp,
                        inflammation_aligned.crp IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    rhythm_aligned AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.rhythm.subject_id AS subject_id,
            mimiciv_derived.rhythm.charttime AS charttime,
            mimiciv_derived.rhythm.heart_rhythm AS heart_rhythm,
            mimiciv_derived.rhythm.ectopy_type AS ectopy_type,
            mimiciv_derived.rhythm.ectopy_frequency AS ectopy_frequency,
            mimiciv_derived.rhythm.ectopy_type_secondary AS ectopy_type_secondary,
            mimiciv_derived.rhythm.ectopy_frequency_secondary AS ectopy_frequency_secondary
        FROM mimiciv_derived.rhythm
            JOIN mimiciv_derived.icustay_detail ON mimiciv_derived.rhythm.subject_id = mimiciv_derived.icustay_detail.subject_id
            AND mimiciv_derived.rhythm.charttime >= mimiciv_derived.icustay_detail.icu_intime
            AND mimiciv_derived.rhythm.charttime <= mimiciv_derived.icustay_detail.icu_outtime
        WHERE mimiciv_derived.icustay_detail.stay_id IS NOT NULL
    ),
    rhythm_tokenized AS (
        SELECT rhythm_aligned.stay_id AS stay_id,
            rhythm_aligned.charttime AS charttime,
            tokens.token_label AS token_label,
            tokens.token_value AS token_value
        FROM rhythm_aligned
            JOIN LATERAL (
                VALUES (
                        concat(
                            'rhythm.heart_rhythm.',
                            CAST(rhythm_aligned.heart_rhythm AS TEXT)
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        rhythm_aligned.heart_rhythm IS NULL
                    ),
                    (
                        concat(
                            'rhythm.ectopy_type.',
                            CAST(rhythm_aligned.ectopy_type AS TEXT)
                        ),
                        CAST(NULL AS DOUBLE PRECISION),
                        rhythm_aligned.ectopy_type IS NULL
                    )
            ) AS tokens (token_label, token_value, token_null) ON true
        WHERE NOT tokens.token_null
    ),
    hour_events AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            generate_series(
                date_trunc(
                    'hour',
                    mimiciv_derived.icustay_detail.icu_intime
                ),
                date_trunc(
                    'hour',
                    mimiciv_derived.icustay_detail.icu_outtime
                ),
                '1 hour'
            ) AS charttime,
            concat(
                'hour.',
                EXTRACT(
                    hour
                    FROM generate_series(
                            date_trunc(
                                'hour',
                                mimiciv_derived.icustay_detail.icu_intime
                            ),
                            date_trunc(
                                'hour',
                                mimiciv_derived.icustay_detail.icu_outtime
                            ),
                            '1 hour'
                        )
                )
            ) AS token_label,
            CAST(NULL AS DOUBLE PRECISION) AS token_value
        FROM mimiciv_derived.icustay_detail
    ),
    admission_events AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.icustay_detail.icu_intime AS charttime,
            'admission' AS token_label,
            CAST(NULL AS DOUBLE PRECISION) AS token_value
        FROM mimiciv_derived.icustay_detail
    ),
    discharge_events AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.icustay_detail.icu_outtime AS charttime,
            'discharge' AS token_label,
            CAST(NULL AS DOUBLE PRECISION) AS token_value
        FROM mimiciv_derived.icustay_detail
    ),
    mort_events AS (
        SELECT mimiciv_derived.icustay_detail.stay_id AS stay_id,
            mimiciv_derived.icustay_detail.dischtime AS charttime,
            'mort' AS token_label,
            CAST(NULL AS DOUBLE PRECISION) AS token_value
        FROM mimiciv_derived.icustay_detail
        WHERE mimiciv_derived.icustay_detail.hospital_expire_flag = 1
    ),
    union_tokenized AS (
        SELECT vitalsign_tokenized.stay_id AS stay_id,
            vitalsign_tokenized.charttime AS charttime,
            vitalsign_tokenized.token_label AS token_label,
            vitalsign_tokenized.token_value AS token_value
        FROM vitalsign_tokenized
        UNION ALL
        SELECT crrt_tokenized.stay_id AS stay_id,
            crrt_tokenized.charttime AS charttime,
            crrt_tokenized.token_label AS token_label,
            crrt_tokenized.token_value AS token_value
        FROM crrt_tokenized
        UNION ALL
        SELECT chemistry_tokenized.stay_id AS stay_id,
            chemistry_tokenized.charttime AS charttime,
            chemistry_tokenized.token_label AS token_label,
            chemistry_tokenized.token_value AS token_value
        FROM chemistry_tokenized
        UNION ALL
        SELECT complete_blood_count_tokenized.stay_id AS stay_id,
            complete_blood_count_tokenized.charttime AS charttime,
            complete_blood_count_tokenized.token_label AS token_label,
            complete_blood_count_tokenized.token_value AS token_value
        FROM complete_blood_count_tokenized
        UNION ALL
        SELECT blood_differential_tokenized.stay_id AS stay_id,
            blood_differential_tokenized.charttime AS charttime,
            blood_differential_tokenized.token_label AS token_label,
            blood_differential_tokenized.token_value AS token_value
        FROM blood_differential_tokenized
        UNION ALL
        SELECT bg_tokenized.stay_id AS stay_id,
            bg_tokenized.charttime AS charttime,
            bg_tokenized.token_label AS token_label,
            bg_tokenized.token_value AS token_value
        FROM bg_tokenized
        UNION ALL
        SELECT cardiac_marker_tokenized.stay_id AS stay_id,
            cardiac_marker_tokenized.charttime AS charttime,
            cardiac_marker_tokenized.token_label AS token_label,
            cardiac_marker_tokenized.token_value AS token_value
        FROM cardiac_marker_tokenized
        UNION ALL
        SELECT coagulation_tokenized.stay_id AS stay_id,
            coagulation_tokenized.charttime AS charttime,
            coagulation_tokenized.token_label AS token_label,
            coagulation_tokenized.token_value AS token_value
        FROM coagulation_tokenized
        UNION ALL
        SELECT enzyme_tokenized.stay_id AS stay_id,
            enzyme_tokenized.charttime AS charttime,
            enzyme_tokenized.token_label AS token_label,
            enzyme_tokenized.token_value AS token_value
        FROM enzyme_tokenized
        UNION ALL
        SELECT icp_tokenized.stay_id AS stay_id,
            icp_tokenized.charttime AS charttime,
            icp_tokenized.token_label AS token_label,
            icp_tokenized.token_value AS token_value
        FROM icp_tokenized
        UNION ALL
        SELECT urine_output_tokenized.stay_id AS stay_id,
            urine_output_tokenized.charttime AS charttime,
            urine_output_tokenized.token_label AS token_label,
            urine_output_tokenized.token_value AS token_value
        FROM urine_output_tokenized
        UNION ALL
        SELECT ventilator_setting_tokenized.stay_id AS stay_id,
            ventilator_setting_tokenized.charttime AS charttime,
            ventilator_setting_tokenized.token_label AS token_label,
            ventilator_setting_tokenized.token_value AS token_value
        FROM ventilator_setting_tokenized
        UNION ALL
        SELECT inflammation_tokenized.stay_id AS stay_id,
            inflammation_tokenized.charttime AS charttime,
            inflammation_tokenized.token_label AS token_label,
            inflammation_tokenized.token_value AS token_value
        FROM inflammation_tokenized
        UNION ALL
        SELECT rhythm_tokenized.stay_id AS stay_id,
            rhythm_tokenized.charttime AS charttime,
            rhythm_tokenized.token_label AS token_label,
            rhythm_tokenized.token_value AS token_value
        FROM rhythm_tokenized
        UNION ALL
        SELECT hour_events.stay_id AS stay_id,
            hour_events.charttime AS charttime,
            hour_events.token_label AS token_label,
            hour_events.token_value AS token_value
        FROM hour_events
        UNION ALL
        SELECT admission_events.stay_id AS stay_id,
            admission_events.charttime AS charttime,
            admission_events.token_label AS token_label,
            admission_events.token_value AS token_value
        FROM admission_events
        UNION ALL
        SELECT discharge_events.stay_id AS stay_id,
            discharge_events.charttime AS charttime,
            discharge_events.token_label AS token_label,
            discharge_events.token_value AS token_value
        FROM discharge_events
        UNION ALL
        SELECT mort_events.stay_id AS stay_id,
            mort_events.charttime AS charttime,
            mort_events.token_label AS token_label,
            mort_events.token_value AS token_value
        FROM mort_events
    ),
    token_values AS (
        SELECT union_tokenized.stay_id AS stay_id,
            union_tokenized.charttime AS charttime,
            union_tokenized.token_label AS token_label,
            union_tokenized.token_value AS token_value,
            CAST(
                floor(
                    percent_rank() OVER (
                        PARTITION BY union_tokenized.token_label
                        ORDER BY union_tokenized.token_value
                    ) * 10
                ) AS INTEGER
            ) AS token_value_disc
        FROM union_tokenized
        ORDER BY union_tokenized.stay_id,
            union_tokenized.charttime
    ),
    med_derived_events_combined AS (
        SELECT med_values.stay_id AS stay_id,
            med_values.charttime AS charttime,
            med_values.token_label AS token_label,
            med_values.dose AS token_value,
            med_values.token_value_disc AS token_value_disc,
            med_values.uom_label AS uom_label
        FROM med_values
        UNION ALL
        SELECT token_values.stay_id AS stay_id,
            token_values.charttime AS charttime,
            token_values.token_label AS token_label,
            token_values.token_value AS token_value,
            token_values.token_value_disc AS token_value_disc,
            NULL AS uom_label
        FROM token_values
    ),
    numbered_events AS (
        SELECT med_derived_events_combined.stay_id AS stay_id,
            med_derived_events_combined.charttime AS charttime,
            med_derived_events_combined.token_label AS token_label,
            med_derived_events_combined.token_value AS token_value,
            med_derived_events_combined.token_value_disc AS token_value_disc,
            med_derived_events_combined.uom_label AS uom_label,
            row_number() OVER (
                PARTITION BY med_derived_events_combined.stay_id,
                med_derived_events_combined.charttime
                ORDER BY med_derived_events_combined.token_label,
                    med_derived_events_combined.token_value_disc
            ) AS event_idx
        FROM med_derived_events_combined
    ),
    token_stream AS (
        SELECT numbered_events.stay_id AS stay_id,
            numbered_events.charttime AS charttime,
            numbered_events.token_label AS token,
            numbered_events.event_idx AS event_idx,
            1 AS sort_order
        FROM numbered_events
        UNION ALL
        SELECT numbered_events.stay_id AS stay_id,
            numbered_events.charttime AS charttime,
            numbered_events.uom_label AS token,
            numbered_events.event_idx AS event_idx,
            2 AS sort_order
        FROM numbered_events
        WHERE numbered_events.uom_label IS NOT NULL
        UNION ALL
        SELECT numbered_events.stay_id AS stay_id,
            numbered_events.charttime AS charttime,
            concat(
                'magnitude.',
                CAST(numbered_events.token_value_disc AS TEXT)
            ) AS token,
            numbered_events.event_idx AS event_idx,
            3 AS sort_order
        FROM numbered_events
        WHERE numbered_events.token_value IS NOT NULL
        ORDER BY stay_id,
            charttime,
            event_idx,
            sort_order
    ),
    unique_tokens AS (
        SELECT token_stream.token AS token
        FROM token_stream
        GROUP BY token_stream.token
    ),
    d_tokens AS (
        SELECT row_number() OVER (
                ORDER BY unique_tokens.token
            ) AS token_id,
            unique_tokens.token AS token
        FROM unique_tokens
    )
    SELECT token_stream.stay_id,
        token_stream.charttime,
        d_tokens.token_id,
        token_stream.token
    FROM token_stream
        JOIN d_tokens ON d_tokens.token = token_stream.token
);
CREATE INDEX IF NOT EXISTS sid_time ON mimiciv_local.tokenevents(stay_id, charttime);
DROP TABLE IF EXISTS mimiciv_local.d_tokens;
CREATE TABLE mimiciv_local.d_tokens AS (
    SELECT token_id,
        token
    FROM mimiciv_local.tokenevents
    GROUP BY token_id,
        token
);
CREATE UNIQUE INDEX IF NOT EXISTS token_id ON mimiciv_local.d_tokens(token_id);